#include <stdlib.h>
#include <zephyr/kernel.h>
#include <zephyr/shell/shell.h>

#include "cryptoauthlib.h"

#include <zephyr/logging/log.h>
LOG_MODULE_REGISTER(crypto, LOG_LEVEL_DBG);

static ATCAIfaceCfg iface_config = {
    .iface_type            = ATCA_I2C_IFACE,
    .cfg_data              = (void *)"i2c@40005400",
    .devtype               = ATECC608A,
    {
        .atcai2c           = {
        .address       = 0xC0,
        .bus           = 0,
        .baud          = 400000,
        },
    },
    .wake_delay            = 2000,
    .rx_retries            = 20
};
#if 0
static uint8_t atecc608_config_data[ATCA_ECC_CONFIG_SIZE] = {
    /* 000 */ 0x01, 0x23, 0x00, 0x00, 0x00, 0x00, 0x60, 0x00, 0x04, 0x05, 0x06, 0x07, 0xEE, 0x01, 0x01, 0x00,
    /* 016 */ 0xC0, 0x00, 0xA1, 0x00, 0xAF, 0x2F, 0xC4, 0x44, 0x87, 0x20, 0xC4, 0xF4, 0x8F, 0x0F, 0x0F, 0x0F,
    /* 032 */ 0x9F, 0x8F, 0x83, 0x64, 0xC4, 0x44, 0xC4, 0x64, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F, 0x0F,
    /* 048 */ 0x0F, 0x0F, 0x0F, 0x0F, 0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF,
    /* 064 */ 0x00, 0x00, 0x00, 0x00, 0xFF, 0x84, 0x03, 0xBC, 0x09, 0x69, 0x76, 0x00, 0x00, 0x00, 0x00, 0x00,
    /* 096 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0x0E, 0x40, 0x00, 0x00, 0x00, 0x00,
    /* 112 */ 0x33, 0x00, 0x1C, 0x00, 0x13, 0x00, 0x1C, 0x00, 0x3C, 0x00, 0x3A, 0x10, 0x1C, 0x00, 0x33, 0x00,
    /* 128 */ 0x1C, 0x00, 0x1C, 0x00, 0x38, 0x00, 0x30, 0x00, 0x3C, 0x00, 0x3C, 0x00, 0x32, 0x00, 0x30, 0x00
};
#elif 1
/* 
    get the chip form taobao.
        0, 1, 2 : P256 NIST ECC key, only ReadKey is different.
            0 : 3 -->
            1 : 7 --> mbedTLS ECDH.
            2 : F -->
                Bit 0: External signatures of arbitrary messages are enabled.
                Bit 1: Internal signatures of messages generated by GenDig or GenKey are enabled.
                Bit 2: ECDH operation is permitted for this key.
                Bit 3: If clear, then ECDH master secret may be output in the clear. If set, then master
                secret may be written into slot N|1. Ignored if Bit 2 is zero.
        
        8, 9, 10, 11, 12, 13, 14 : transparent read and write.
            slot config : 0x0000
            key  config : 0x003C
        
        15 : 
            slot config : 0x8FAF
            key  config : 0x001C

*/
static uint8_t atecc608_config_data[ATCA_ECC_CONFIG_SIZE] = {
    /* 000 */ 0x01, 0x23, 0x87, 0xA9, 0x00, 0x00, 0x60, 0x02,  0xA7, 0xD7, 0x27, 0xF7, 0xEE, 0xC1, 0x5D, 0x00, 
    /* 016 */ 0xC0, 0x00, 0x00, 0x00, 0x83, 0x20, 0x87, 0x20,  0x8F, 0x20, 0xC4, 0x8F, 0x8F, 0x8F, 0x8F, 0x8F, 
    /* 032 */ 0x9F, 0x8F, 0xAF, 0x8F, 0x00, 0x00, 0x00, 0x00,  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /* 048 */ 0x00, 0x00, 0xAF, 0x8F, 0xFF, 0xFF, 0xFF, 0xFF,  0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF, 
    /* 064 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /* 080 */ 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 
    /* 096 */ 0x33, 0x00, 0x33, 0x00, 0x33, 0x00, 0x1C, 0x00,  0x1C, 0x00, 0x1C, 0x00, 0x1C, 0x00, 0x1C, 0x00, 
    /* 112 */ 0x3C, 0x00, 0x3C, 0x00, 0x3C, 0x00, 0x3C, 0x00,  0x3C, 0x00, 0x3C, 0x00, 0x3C, 0x00, 0x1C, 0x00,
};
#endif

int _crypto_atecc608_init()
{
    ATCA_STATUS status = atcab_init(&iface_config);
    if (status != ATCA_SUCCESS)
    {
        LOG_ERR("atcab_init() failed: %02x", status);
        return -ENODEV;
    }
    
    return 0;
}

static int _read_config()
{
    ATCA_STATUS status;
    uint8_t config[256] = {0};
    size_t config_size = 0;
    uint8_t zone = ATCA_ZONE_CONFIG;

    do
    {
        status = atcab_get_zone_size(zone, 0, &config_size);
        if (status != ATCA_SUCCESS)
        {
            LOG_ERR("atcab_get_zone_size() failed: %02x\r\n", status);
            break;
        }

        status = atcab_read_config_zone(config);
        if (status != ATCA_SUCCESS)
        {
            LOG_ERR("atcab_read_config_zone() failed: %02x\r\n", status);
            break;
        }

        LOG_HEXDUMP_INF(config, config_size, "config");
        #if 1
            for(uint8_t i=0;i<config_size;)
            {
                if(i%16 == 0)
                {
                    printf("/* %03d */ ", i);
                }
                printf("0x%02X, ", config[i]);
                i++;
                if(i%8==0 && i%16!=0)
                {
                    printf(" ");
                }
                if(i%16==0)
                {
                    printf("\r\n");
                }
            }
        #endif
    }
    while (0);
    
    LOG_HEXDUMP_INF(config + 21, 32, "slot config");
    LOG_HEXDUMP_INF(config + 96, 32, "key config");

    return 0;
}

static int _read_data()
{
    ATCA_STATUS status;
    size_t slot_size = 0;
    uint8_t buffer[512] = {0};

    for(uint16_t slot=8; slot<15;slot++)
    {
        status = atcab_get_zone_size(ATCA_ZONE_DATA, slot, &slot_size);
        if (status != ATCA_SUCCESS) {
            LOG_ERR("atcab_get_zone_size failed with ret=%d", status);
            continue;
        }
        LOG_INF("slot:%d --- size:%d", slot, slot_size);
        status = atcab_read_zone(ATCA_ZONE_DATA, slot, 0, 0, buffer, 32);

        if (status == ATCA_SUCCESS) {
            LOG_HEXDUMP_INF(buffer, 32, "RX");
        } else if (status == ATCA_NOT_LOCKED) {
            LOG_WRN("slot not locked\n");
        } else {
            LOG_ERR("atcab_read_zone failed with ret=%d", status);
        }
    }

    return 0;
}

static int _write_data()
{
    uint8_t key[32] = {0};
    ATCA_STATUS status;

    strcpy(key, "Hello, My name is Bruce Zhao.");

    status = atcab_write_zone(ATCA_ZONE_DATA, 9, 0, 0, key, 32);

    if (status == ATCA_SUCCESS) {
        LOG_INF("slot 9 write success.");
    } else {
        LOG_ERR("slot 9 write failed with ret=%d", status);
    }

    return 0;
}

static int _lock_config_crypto_atecc608()
{
    ATCA_STATUS status;
    bool is_locked = false;

    if ((status = atcab_is_config_locked(&is_locked)) != ATCA_SUCCESS)
    {
        LOG_ERR("atcab_is_config_locked() failed with ret=0x%08X", status);
    }
    else
    {
        LOG_INF("config zone: %s", is_locked ? "locked" : "unlocked");
    }

    if(is_locked == true)
    {
        return 0;
    }

    status = atcab_lock_config_zone();
    if(status == ATCA_SUCCESS)
    {
        atcab_wakeup();
        LOG_INF("ATECC608 locked success.");
        return 0;
    }
    else{
        
        LOG_ERR("ATECC608 locked failed with ret=%d", status);
        return -EAGAIN;
    }
}

static int _lock_data_crypto_atecc608()
{
    ATCA_STATUS status;
    bool is_locked = false;

    if ((status = atcab_is_data_locked(&is_locked)) != ATCA_SUCCESS)
    {
        LOG_ERR("atcab_is_data_locked() failed with ret=0x%08X", status);
    }
    else
    {
        LOG_INF("data zone: %s", is_locked ? "locked" : "unlocked");
    }

    if(is_locked == true)
    {
        return 0;
    }

    status = atcab_lock_data_zone();
    if(status == ATCA_SUCCESS)
    {
        atcab_wakeup();
        LOG_INF("ATECC608 data zone locked success.");
        return 0;
    }
    else{
        
        LOG_ERR("ATECC608 data zone locked failed with ret=%d", status);
        return -EAGAIN;
    }
}

static int _verify_aes(void) {
    ATCA_STATUS status;
    uint8_t plaintext[16] = {0};
    uint8_t ciphertext[16] = {0};
    for(uint8_t slot=0;slot<15;slot++)
    {
        status = atcab_aes_encrypt(slot, 0, plaintext, ciphertext);

        if (status == ATCA_SUCCESS) {
            LOG_INF("AES crypto success.");
            LOG_HEXDUMP_INF(ciphertext, 16, "AES Ciphertext");
        } else {
            LOG_ERR("AES crypto failed with ret=%d", status);
        }
    }

    return 0;
}

static int _generate_ecc_key(int slot_id)
{
    ATCA_STATUS status;
    uint8_t buffer[64] = {0};

    status = atcab_genkey(slot_id, buffer);
    if (status == ATCA_SUCCESS) {
        LOG_INF("ECC genkey on slot %d success.", slot_id);
        LOG_HEXDUMP_INF(buffer, sizeof(buffer), "public key");
    }
    else{
        LOG_ERR("atcab_genkey failed with ret=%d", status);
        return status;
    }

    status = atcab_get_pubkey(slot_id, buffer);
    if(status == ATCA_SUCCESS)
    {
        LOG_HEXDUMP_INF(buffer, sizeof(buffer), "public key check");
    }
    else
    {
        LOG_ERR("atcab_get_pubkey failed with ret=%d", status);
    }

    return 0;
}

static int _ecc_hardware_test(void) {
    ATCA_STATUS status;
    uint8_t pubkey[64] = {0};
    uint8_t msg_hash[32] = {0};
    uint8_t signature[64] = {0};
    bool is_verified = false;

    memset(msg_hash, 0xAA, 32);

    status = atcab_genkey(1, pubkey);
    
    if(status == ATCA_SUCCESS)
    {
        LOG_INF("key generate success.");
        status = atcab_sign(1, msg_hash, signature);

        if (status == ATCA_SUCCESS) {
            LOG_INF("sign success");
            status = atcab_verify_extern(msg_hash, signature, pubkey, &is_verified);
            if(status == ATCA_SUCCESS)
            {
                LOG_INF("verify status : %s", is_verified == true?"true":"false");
            }
            else
            {
                LOG_ERR("atcab_verify_extern failed with ret=%d", status);
            }
        }
        else{
            LOG_ERR("atcab_sign failed with ret=%d", status);
        }
    }

    return 0;
}

static void _ecdsa_software_test(void) {
    extern int _ecdsa();
    _ecdsa();
}

static int _ecdhe_software_test()
{
    extern int _ecdhe();
    _ecdhe();

    return 0;
}

static void _crypto_ecdhe()
{
    uint8_t slot_num = 1;
    uint8_t public_key[ATCA_PUB_KEY_SIZE] = {0};
    uint8_t shared_key[ATCA_KEY_SIZE] = {0};
    uint8_t buffer[ATCA_PUB_KEY_SIZE] = {0};
    ATCA_STATUS status;

    /* only slot 1 is valid. */

    for(slot_num=1;slot_num<2;slot_num++)
    {
        LOG_INF("slot number : %d", slot_num);
        status = atcab_genkey(slot_num, public_key);
        LOG_INF("ret : %d", status);

        LOG_HEXDUMP_INF(public_key, sizeof(public_key), "public");

        memcpy(buffer, public_key, ATCA_PUB_KEY_SIZE);
        
        status = atcab_ecdh(slot_num, public_key, shared_key);
        LOG_INF("ret : %d", status);
        if(status == ATCA_SUCCESS)
        {
            LOG_INF("ECDH success! shared secret generated.");
            LOG_HEXDUMP_INF(shared_key, sizeof(shared_key), "key");
        }
        else
        {
            LOG_ERR("atcab_ecdh() failed with ret=0x%08X", status);
        }
    }
}

static void atecc608_check_slot_config(uint8_t *config, uint8_t slot)
{
    uint16_t slot_config = 0;
    uint16_t key_config = 0;
    uint8_t *p = config + 20;
    uint8_t offset = 2*slot;
    
    LOG_INF("checking slot %d...", slot);
    p += offset;
    slot_config = (*p << 0) | (*(p+1) <<8);
    LOG_INF("slot config : 0x%04X", slot_config);

    uint8_t WriteConfig = (slot_config>>12) & 0x0F;
    uint8_t WriteKey    = (slot_config>>8) & 0x0F;
    uint8_t IsSecret    = (slot_config>>7) & 0x01;
    uint8_t EncryptRead = (slot_config>>6) & 0x01;
    uint8_t LimitedUse  = (slot_config>>5) & 0x01;
    uint8_t NoMac       = (slot_config>>4) & 0x01;
    uint8_t ReadKey     = (slot_config>>0) & 0x0F;

    LOG_INF("  WriteConfig : 0x%X", WriteConfig);
    LOG_INF("  WriteKey    : 0x%X", WriteKey);
    LOG_INF("  IsSecret    : 0x%X", IsSecret);
    LOG_INF("  EncryptRead : 0x%X", EncryptRead);
    LOG_INF("  LimitedUse  : 0x%X", LimitedUse);
    LOG_INF("  NoMac       : 0x%X", NoMac);
    LOG_INF("  ReadKey     : 0x%X", ReadKey);
    

    p = config + 96;
    p += offset;
    
    key_config = (*p << 0) | (*(p+1) <<8);
    LOG_INF("key config : 0x%04X", key_config);

    uint8_t X509id            = (key_config>>14) & 0x03;
    uint8_t RFU               = (key_config>>13) & 0x01;
    uint8_t PersistentDisable = (key_config>>12) & 0x01;
    uint8_t AuthKey           = (key_config>>8) & 0x0F;
    uint8_t ReqAuth           = (key_config>>7) & 0x01;
    uint8_t ReqRandom         = (key_config>>6) & 0x01;
    uint8_t Lockable          = (key_config>>5) & 0x01;
    uint8_t KeyType           = (key_config>>2) & 0x07;
    uint8_t PubInfo           = (key_config>>1) & 0x01;
    uint8_t Private           = (key_config>>0) & 0x01;

    LOG_INF("  X509id            : 0x%X", X509id);
    LOG_INF("  RFU               : 0x%X", RFU);
    LOG_INF("  PersistentDisable : 0x%X", PersistentDisable);
    LOG_INF("  AuthKey           : 0x%X", AuthKey);
    LOG_INF("  ReqAuth           : 0x%X", ReqAuth);
    LOG_INF("  ReqRandom         : 0x%X", ReqRandom);
    LOG_INF("  Lockable          : 0x%X", Lockable);
    LOG_INF("  KeyType           : 0x%X", KeyType);
    
    switch(KeyType)
    {
        case 4:
            LOG_WRN("    P256 NIST ECC key");
        break;
        case 5:
            LOG_INF("    RFU");
        break;
        case 6:
            LOG_INF("    AES key");
        break;
        case 7:
            LOG_INF("    SHA key or other data");
        break;
    }
    
    LOG_INF("  PubInfo           : 0x%X", PubInfo);
    LOG_INF("  Private           : 0x%X", Private);
}

void atecc608_config_summary(uint8_t *config)
{
    uint8_t AES_Enable = config[13]&0x01;
    LOG_INF("AES_Enable : %d", AES_Enable);

    uint8_t I2C_Enable = config[14]&0x01;
    LOG_INF("I2C_Enable : %d", I2C_Enable);

    uint8_t I2C_Address = config[16];
    if(((config[19]&0x01) == 1) && (config[85] != 0))
    {
        LOG_WRN("I2C_Address : 0x%02X", config[85]);
    }
    else
    {
        LOG_INF("I2C_Address : 0x%02X", I2C_Address);
    }

    uint8_t CountMatch = config[18];
    LOG_INF("CountMatch enable : %d --- key : %d", (CountMatch>>0)&0x01, (CountMatch>>4)&0x0F);

    uint8_t UseLock = config[68];
    LOG_INF("UseLock enable (confusion): %d --- key : %d", (UseLock>>0)&0x0F, (UseLock>>4)&0x0F);

    uint8_t VolatileKeyPermission = config[69];
    LOG_INF("VolatileKeyPermission enable : %d --- key : %d", (VolatileKeyPermission>>7)&0x01, (VolatileKeyPermission>>0)&0x0F);

    uint16_t SecureBoot = (config[70] << 0) | ( config[71] <<8);
    LOG_INF("Secure Boot Configuration : 0x%04X", SecureBoot);
    uint8_t SecureBootPubKey = (SecureBoot>>12) & 0x0F;
    LOG_INF("  SecureBootPubKey : %d", SecureBootPubKey);

    uint8_t SecureBootSigDig = (SecureBoot>>8) & 0x0F;
    LOG_INF("  SecureBootSigDig : %d", SecureBootSigDig);

    uint8_t SecureBootRandNonce = (SecureBoot>>4) & 0x01;
    LOG_INF("  SecureBootRandNonce : %d", SecureBootRandNonce);

    uint8_t SecureBootPersistentEnable = (SecureBoot>>3) & 0x01;
    LOG_INF("  SecureBootPersistentEnable : %d", SecureBootPersistentEnable);

    uint8_t SecureBootMode = (SecureBoot>>0) & 0x03;
    LOG_INF("  SecureBootMode : %d", SecureBootMode);
    switch(SecureBootMode)
    {
        case 0:
            LOG_INF("    \"Disabled\"");
        break;
        case 1:
            LOG_INF("    \"FullBoth\"");
        break;
        case 2:
            LOG_INF("    \"FullSig\"");
        break;
        case 3:
            LOG_INF("    \"FullDig\"");
        break;
        default:
        break;
    }

    uint8_t LockValue = config[86];
    LOG_INF("LockValue : 0x%02X", LockValue);

    uint8_t LockConfig = config[87];
    LOG_INF("LockConfig : 0x%02X", LockConfig);

    uint16_t SlotLocked = (config[88] << 0) | ( config[89] <<8);
    LOG_INF("SlotLocked : 0x%04X", SlotLocked);

    uint16_t IO_Protection = (config[90] << 0) | ( config[91] <<8);
    LOG_INF("IO Protection : 0x%04X", IO_Protection);

    uint8_t io_protection_enable = (IO_Protection>>1) & 0x01;
    LOG_INF("  IO Protection Enable : %d", io_protection_enable);

    uint8_t ecdh_port = (IO_Protection>>8) & 0x03;
    LOG_INF("  ECDH Port : %d", ecdh_port);

    uint8_t kdf_port = (IO_Protection>>10) & 0x03;
    LOG_INF("  KDF Port : %d", kdf_port);

    uint8_t io_protection_key = (IO_Protection>>12) & 0x0F;
    LOG_INF("  IO Protection key : %d", io_protection_key);
}

static int example_crypto_operations(const struct shell *sh, size_t argc, char *argv[])
{
    int operation = atoi(argv[1]);
    
    LOG_DBG("operation %d selected", operation);

    if(operation == 0)
    {
        ATCA_STATUS status;
        bool is_locked = false;

        {
            if ((status = atcab_is_config_locked(&is_locked)) != ATCA_SUCCESS)
            {
                LOG_ERR("atcab_is_config_locked() failed with ret=0x%08X", status);
            }
            else
            {
                LOG_INF("config zone: %s", is_locked ? "locked" : "unlocked");
            }
        }

        {
            if ((status = atcab_is_data_locked(&is_locked)) != ATCA_SUCCESS)
            {
                LOG_ERR("atcab_is_data_locked() failed with ret=0x%08X", status);
            }
            else
            {
                LOG_INF("data zone: %s", is_locked ? "locked" : "unlocked");
            }
        }

        {
            uint8_t revision[4] = {0};

            status = atcab_info(revision);
            if (status != ATCA_SUCCESS)
            {
                LOG_ERR("atcab_info() failed with ret=0x%08X", status);
            }
            LOG_HEXDUMP_INF(revision, sizeof(revision), "version");
        }

        {
            uint8_t sernum[9] = {0};

            status = atcab_read_serial_number(sernum);
            if (status != ATCA_SUCCESS)
            {
                LOG_ERR("atcab_read_serial_number() failed with ret=0x%08X", status);
            }

            LOG_HEXDUMP_INF(sernum, sizeof(sernum), "serial number");
        }

        LOG_INF("ATECC608A init success.");
    }
    else if(operation == 1)
    {
        _read_config();
    }
    else if(operation == 2)
    {
        _read_data();
    }
    else if(operation == 3)
    {
        _write_data();
    }
    else if(operation == 4)
    {
        _verify_aes();
    }
    else if(operation == 5)
    {
        if(argc<3)
        {
            return 0;
        }
        _generate_ecc_key(atoi(argv[2]));
    }
    else if(operation == 6)
    {
        _ecc_hardware_test();
    }
    else if(operation == 7)
    {
        _ecdsa_software_test();
    }
    else if(operation == 8)
    {
        _ecdhe_software_test();
    }
    else if(operation == 9)
    {
        _crypto_ecdhe();
    }
    else if(operation == 10)
    {
        if(argc<3)
        {
            return 0;
        }
        atecc608_check_slot_config(atecc608_config_data, atoi(argv[2]));
    }
    else if(operation == 11)
    {
        atecc608_config_summary(atecc608_config_data);
    }
    else if(operation == 10086)
    {
    /* 
        [00:00:09.335,000] <dbg> crypto: example_crypto_operations: operation 10086 selected
        [00:00:09.349,000] <inf> crypto: config zone: unlocked
        [00:00:09.380,000] <inf> crypto: ATECC608 locked success.
    */
        _lock_config_crypto_atecc608();
    }
    else if(operation == 1008611)
    {
        _lock_data_crypto_atecc608();
    }
    else 
    {
        LOG_DBG("unknown operation");
    }

    return 0;
}

SHELL_STATIC_SUBCMD_SET_CREATE(crypto_commands,
	SHELL_CMD(num, NULL,
		"operation",
		example_crypto_operations),
	SHELL_SUBCMD_SET_END
);

SHELL_CMD_REGISTER(crypto, &crypto_commands,
		   "example for crypto", NULL);

